#Application URL
url= http://localhost/orangehrm/web/index.php/auth/login

#Browser Configuration
browser= chrome

#Credentials
username = orangehrm_shubh
password = Shubh@1234

#ImplicitWai
implicitWait =100

#ExplicitWai
explicitWait =30